services:
  api:
    build: .
    command: uvicorn src.api:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8000:80
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./src:/api/src # This enables hot reloading for dev purposes
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ecommerce:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  ecommerce:
