version: '3'
services:
  api:
    build: .
    command: uvicorn src.api:app --host 0.0.0.0 --port 80 --reload # dev
    ports:
      - 8000:80
    restart: always
    environment:
      POSTGRES_URL: postgresql://${DB_USER}:${DB_PASSWD}@postgres/${DB_NAME}
    volumes:
      - .:/api # dev
    depends_on:
      - schema
  schema:
    build: ./schema
    depends_on:
      - postgres
    command: sqitch deploy db:pg://${DB_USER}:${DB_PASSWD}@postgres/${DB_NAME}
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  ecommerce:
