services:
  api:
    build: .
    ports:
      - 8000:80
    restart: always
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ecommerce:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: lwieckowski@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  ecommerce:
